### ISSUE TITLE
"app" does not connect to "mongo".

### ISSUE THREAD

**Issue by mosesmosheh** [Project-Prismatica/Emergence#5]
### Notes
1. Following the guides at http://prismatica.io/guides
2. I have corrected docker-compose and Dockerfile (see issue #4) and then updated the paths in settings.json (see below) and then executre docker-compose up

### What's gone wonky
_mongo_ starts correctly and runs. When _app_ tries to start, it cannot connect to mongo. The error message I receive back:
`MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
`
At this point it tries to restart app, gets the same error, and catches in this loop.

### A bit of debugging so far
- I can use mongo cli to connect to the mongo server. There is no authentication, so it appears to be running OK and in theory app should be able to connect.
- I can use the mongo cli running in a from a different docker container to connect in the same way to the mongo db.
- If I stop mongo and comment it out from docker-compose, then start netcat listening on port 27017 instead, when I try to execute Docker again no output appears in netcat, which suggests it isn't "getting out" properly.

### Files
My files (following corrections notes in issue #4) look like this...
**docker-compose.yml**
```
version: "2.1"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "0.0.0.0:29001:29001"
    expose:
      - "29001"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "127.0.0.1:27017:27017"
```

**Dockerfile**
```
ROM node:latest
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package.json /usr/src/app/
COPY . /usr/src/app
RUN npm install
EXPOSE 29001
CMD [ "ifconfig" ]
CMD [ "npm", "install" ]
CMD [ "npm", "rebuild" ]
CMD [ "npm", "start" ]
```

**settings.json**
```
{
  "Description": "Settings Variables for PRISMatica",
  "lwd": "/home/ubuntu/Emergence",
  "dataDir": "/home/ubuntu/Emergence/data",
  "rpcHost": "localhost",
  "rpcPort": "8010"
}
```
